title: Personal Website
author: Ade Putra
email: permana.adeputra@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My name is Ade Putra. I am a product designer based in Malang, Indonesia.

# social links
twitter_username: adbk_ # DO NOT include the @ character, or else the build will fail!
github_username:  hello-ade # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
